apiVersion: v1
data:
  rclone.conf : |
    [spaces-ams3]
    type = s3
    env_auth = false
    access_key_id = YLQNLIVGYG5UC4VQMYVY
    secret_access_key = kkwwsZl/KpaECjKgvTvbk45hRVl5oCofFi4wkxcGnBQ
    endpoint = ams3.digitaloceanspaces.com
    acl = public-read
    provider = DigitalOcean

kind: ConfigMap
metadata:
  managedFields:
    - apiVersion: v1
  name: cec-reclone-config
  namespace: cec

