apiVersion: v1
kind: Service
metadata:
  name: categories
  namespace: cec
  labels:
    app: categories
spec:
  ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
  selector:
    app: categories
