apiVersion: v1
data:
  .env: |
    BASE_URL=https://prindustry.io/api/v2/in/mgr/
    SOCKET_URL=https://prindustry.io/
    ACCESS_TOKEN=local
    ZEN_EMAIL=it@prindustry.nl
    ZEN_WIDGET_KEY=4d25737f-7569-43dd-8b8e-7d9b61d61237
    ZEN_WIDGET_SECRET=6f0ab499581b125c845087185dc0fa6a
    ZEN_API_TOKEN=8tQyQsnmBdgqiMHwc3OZrjjG2aOGgFiybpH1QeYV
kind: ConfigMap
metadata:
  managedFields:
    - apiVersion: v1
  name: cec-nuxt-config
  namespace: cec
