apiVersion: v1
data:
  .env: |
    PORT=3333
    mongoURI=mongodb+srv://doadmin:fCMt8796jW251eF0@private-db-mongodb-ams3-cec-dev-7aa88438.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-ams3-cec-dev&tlsCAFile=/var/crt/ca-certificate.crt
    APP_KEY=cec.b94d27b9934d3e08a52e52d7da7dabfae7e88ffa992c6b2c71f4920a9f1304e1ab12aace6e4bdfc63e621984d5a56e4d7dbf5008
    HASH_TYPE=sha256
kind: ConfigMap
metadata:
  managedFields:
    - apiVersion: v1
  name: cec-calculation-env
  namespace: cec
