apiVersion: v1
kind: Service
metadata:
  name: marketplace
  namespace: cec
  labels:
    app: marketplace
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: marketplace
